// data.js
const catalogData = [
  // ==========================================================================
  // EIXO A – NORMAS LOCAIS DO ESTADO DE SERGIPE (11 instrumentos)
  // ==========================================================================
  { id: "se-1", title: "Lei nº 2.066/1976 (Estatuto dos Policiais Militares de Sergipe)", year: "1976", level: "Estadual (Sergipe)", theme: "PMSE", nature: "Lei Ordinária Estadual", desc: "Define as bases do regime jurídico da PMSE: hierarquia, disciplina, deveres funcionais e sanções. Fundamenta a estrutura de comando e obediência indispensável ao controle do uso da força no âmbito estadual.", status: "Vigente (com alterações)", link: "alese.se.leg.br" },
  { id: "se-2", title: "Lei nº 4.364/2001 (Regime Disciplinar – Policiais Civis de SE)", year: "2001", level: "Estadual (Sergipe)", theme: "PCSE Disciplina", nature: "Lei Ordinária Estadual", desc: "Pune imprudência, imperícia, negligence e arbitrariedade; agrava sanções quando resultam em morte ou lesão grave. Veda disparo ou manuseio descuidado de arma e sua entrega a não-autorizados. Tipifica como falta grave o maltrato a presos e o uso excessivo/desnecessário de violência.", status: "Vigente", link: "policiacivil.se.gov.br" },
  { id: "se-3", title: "Portaria Normativa nº 003/2013 (Mandados de Reintegração de Posse – PMSE)", year: "2013", level: "Estadual (Sergipe)", theme: "PMSE Operações", nature: "Portaria (ato norm. interno)", desc: "Regulamenta o uso moderado e proporcional da força em reintegrações de posse, definindo protocols de atuação para reduzir risco de violência. Alinha a conduta da PMSE aos princípios do uso progressivo da força.", status: "Vigente", link: "pm.se.gov.br" },
  { id: "se-4", title: "Portaria Normativa nº 022/2015 (Manual do Aluno – CFAP/PMSE)", year: "2015", level: "Estadual (Sergipe)", theme: "PMSE Formação", nature: "Portaria (ato norm. interno)", desc: "Estabelece parâmetros curriculares para formação policial militar, incluindo uso da força, ética e disciplina. A formação técnica é condição para o emprego legítimo de armamento e técnicas coercitivas.", status: "Vigente", link: "pm.se.gov.br" },
  { id: "se-5", title: "Lei Complementar nº 291/2017 (CEDM/SE – Código de Ética e Disciplina)", year: "2017", level: "Estadual (Sergipe)", theme: "Ética e Disciplina Militar", nature: "Lei Complementar Estadual", desc: "Classifica transgressões por gravidade: graves (atos violentos, maltrato a presos); médias (negligência com armamento); leves (descumprimento de normas técnicas). Reafirma o uso da força como atribuição sujeita a limites legais e funcionais.", status: "Vigente", link: "alese.se.leg.br" },
  { id: "se-6", title: "Portaria Normativa nº 014/2019 (Habilitação para Arma de Fogo com Nova Tecnologia – PCSE)", year: "2019", level: "Estadual (Sergipe)", theme: "PCSE Arma de fogo", nature: "Portaria (ato norm. interno)", desc: "Exige proficiência técnica (nota mínima 6,0) para operação de tecnologias letais não-convencionais; restringe o uso a agentes habilitados; mitiga riscos operacionais.", status: "Vigente", link: "policiacivil.se.gov.br" },
  { id: "se-7", title: "Portaria Normativa nº 019/2019 (Procedimentos em Mortes por Intervenção – PCSE)", year: "2019", level: "Estadual (Sergipe)", theme: "PCSE Uso de força letal", nature: "Portaria (ato norm. interno)", desc: "Define protocolo interno de comunicação, preservação de local, instauração de procedimento disciplinar e registro de ocorrência em casos de morte por intervenção policial. Instrumento de accountability e rastreabilidade do uso letal da força pelo Estado em Sergipe.", status: "Vigente", link: "policiacivil.se.gov.br" },
  { id: "se-8", title: "Decreto nº 169/2022 (Acautelamento de Arma Institucional – Servidores Aposentados)", year: "2022", level: "Estadual (Sergipe)", theme: "Arma de fogo / Posse", nature: "Decreto Estadual", desc: "Regula o acautelamento de arma de fogo institucional a servidores policiais civis e militares aposentados. Condiciona o benefício à titularidade de carteira funcional com livre porte. Mantém o rastreamento do armamento público fora do serviço ativo.", status: "Vigente", link: "policiacivil.se.gov.br" },
  { id: "se-9", title: "Emenda Constitucional nº 58/2024 (Constituição do Estado de Sergipe)", year: "2024", level: "Estadual (Sergipe)", theme: "Uso de Força (Constitucional Estadual)", nature: "Emenda Constitucional Estadual", desc: "Emenda constitucional estadual que atualiza o arcabouço normativo sergipano sobre segurança pública e uso da força. Deve ser interpretada em consonância com o Decreto Federal nº 12.341/2024 e a Portaria MJSP nº 855/2025. Conteúdo carece de descrição completa na planilha original.", status: "Vigente", link: "senado.leg.br" },
  { id: "se-10", title: "Portaria Normativa nº 010/2025 (Curso de Condutores de Veículos de Emergência – PCSE)", year: "2025", level: "Estadual (Sergipe)", theme: "PCSE Formação Operacional", nature: "Portaria (ato norm. interno)", desc: "Regulamenta habilitação obrigatória para condução de veículos de emergência por Delegados e Oficiais Investigadores da PCSE. Complementa o sistema de capacitação técnica como condicionante do emprego operacional.", status: "Vigente (2025)", link: "policiacivil.se.gov.br" },
  { id: "se-11", title: "Portaria Normativa nº 011/2025 (Restrição de Arma Ostensiva no CRAI – PCSE)", year: "2025", level: "Estadual (Sergipe)", theme: "PCSE Uso de arma em ambientes prisionais", nature: "Portaria (ato norm. interno)", desc: "Proíbe ingresso de policiais civis do CRAI portando arma ostensiva em ambiente hospitalar na Maternidade Nossa Senhora de Lourdes. Alinha-se ao princípio do uso mínimo e proporcional da força, restringindo o armamento em ambientes sensíveis.", status: "Vigente (2025)", link: "policiacivil.se.gov.br" },

  // ==========================================================================
  // EIXO B – NORMAS CONSTITUCIONAIS FEDERAIS (5 dispositivos/emendas)
  // ==========================================================================
  { id: "fc-1", title: "Art. 5º, III e XLIX (CF/88 – Direitos Fundamentais)", year: "1988", level: "Federal Constitucional", theme: "Direitos Fundamentais e Uso da Força", nature: "Norma Constitucional (Hard Law)", desc: "III: Ninguém será submetido a tortura nem a tratamento desumano ou degradante. XLIX: É assegurado aos presos o respeito à integridade física e moral. Fundamentam os limites absolutos ao uso da força pelo Estado.", status: "Vigente", link: "Informação não disponível" },
  { id: "fc-2", title: "Art. 22, XXII (CF/88 – Competência Privativa da União)", year: "1988", level: "Federal Constitucional", theme: "Competência Legislativa Federal", nature: "Norma Constitucional (Hard Law)", desc: "Competência privativa da União para legislar sobre a Polícia Federal e as Polícias Rodoviária e Ferroviária Federais. Delimita o espaço normativo federal na regulação do uso da força.", status: "Vigente", link: "Informação não disponível" },
  { id: "fc-3", title: "Art. 24, XVI (CF/88 – Competência Concorrente)", year: "1988", level: "Federal Constitucional", theme: "Competência Concorrente Estados/DF", nature: "Norma Constitucional (Hard Law)", desc: "Competência concorrente entre União, Estados e DF para legislar sobre organização, garantias, direitos e deveres das polícias civis. Autoriza os Estados a editarem normas locais sobre uso da força – fundamento normativo das leis sergipanas do catálogo.", status: "Vigente", link: "Informação não disponível" },
  { id: "fc-4", title: "Título V – Arts. 136-144 (CF/88 – Defesa do Estado e das Instituições)", year: "1988", level: "Federal Constitucional", theme: "Forças Armadas e Segurança Pública", nature: "Norma Constitucional (Hard Law)", desc: "Arts. 142-143: Forças Armadas como instrumento de defesa da pátria e GLO. Art. 144: define as forças de segurança pública (PF, PRF, PC, PM, CBM, PP) e o papel das PMs como forças auxiliares e reserva do Exército.", status: "Vigente", link: "Informação não disponível" },
  { id: "fc-5", title: "Emenda Constitucional nº 104/2019 (Criação das Polícias Penais)", year: "2019", level: "Federal Constitucional", theme: "Polícia Penal Federal, Estaduais e Distrital", nature: "Emenda Constitucional (Hard Law)", desc: "Insere as Polícias Penais no rol do art. 144 da CF/88, atribuindo-lhes a segurança dos estabelecimentos penais. Regulamenta o uso da força em contexto prisional.", status: "Vigente", link: "Informação não disponível" },

  // ==========================================================================
  // EIXO C – NORMAS INFRALEGAIS FEDERAIS (12 instrumentos)
  // ==========================================================================
  { id: "fi-1", title: "Decreto-Lei nº 6.880/1980 (Estatuto dos Militares)", year: "1980", level: "Federal Infralegal", theme: "Forças Armadas", nature: "Decreto-Lei Federal", desc: "Define o regime jurídico dos militares das Forças Armadas: direitos, deveres, hierarquia, disciplina e carreira. Estabelece os princípios de hierarquia e disciplina como fundamentos da estrutura militar e uso da força dentro dos limites legais.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-2", title: "Lei nº 9.266/1996 (Carreira de Policial Federal)", year: "1996", level: "Federal Infralegal", theme: "Polícia Federal", nature: "Lei Ordinária Federal", desc: "Cria a carreira de Delegado de Polícia Federal e dispõe sobre a carreira policial federal. Estrutura as carreiras da Polícia Federal, incluindo requisitos de formação, porte de arma e regime de uso da força na esfera federal.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-3", title: "Lei nº 9.654/1998 (Carreira de Policial Rodoviário Federal)", year: "1998", level: "Federal Infralegal", theme: "Polícia Rodoviária Federal", nature: "Lei Ordinária Federal", desc: "Cria a carreira de Policial Rodoviário Federal. Estabelece o regime jurídico dos PRFs, com atribuições de fiscalização, ostensividade, uso da força nas rodovias federais, porte de arma e formação técnica obrigatória.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-4", title: "Lei Complementar nº 97/1999 (Organização, Preparo e Emprego das Forças Armadas)", year: "1999", level: "Federal Infralegal", theme: "Forças Armadas (GLO)", nature: "Lei Complementar Federal", desc: "Normas gerais para organização, preparo e emprego das Forças Armadas. Regulamenta o emprego em Garantia da Lei e da Ordem (GLO): requisitos, autorização presidencial, comando, cessação e responsabilidades. Limites do emprego militar em segurança pública.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-5", title: "Lei nº 10.826/2003 (Estatuto do Desarmamento / SINARM)", year: "2003", level: "Federal Infralegal", theme: "Armas de fogo e munições", nature: "Lei Ordinária Federal", desc: "Regula registro, posse e comercialização de armas de fogo e munições. Cria o SINARM; exclui FA e forças auxiliares de seu âmbito; atribui à PF autorização de porte; delega ao Exército a classificação técnica. Regula o ciclo de vida das armas civis e institucionais.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-6", title: "Lei nº 13.022/2014 (Estatuto Geral das Guardas Municipais)", year: "2014", level: "Federal Infralegal", theme: "Guardas Municipais", nature: "Lei Ordinária Federal", desc: "Regulamenta o art. 144, §8º, da CF/88 — atribuições, limites e estrutura das Guardas Municipais. Define competências das GMs e seus limites constitucionais. Autoriza porte de arma, condicionado à capacitação técnica. Veda atribuições policiais típicas.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-7", title: "Lei nº 13.675/2018 (SUSP – Sistema Único de Segurança Pública)", year: "2018", level: "Federal Infralegal", theme: "Segurança Pública Integrada", nature: "Lei Ordinária Federal", desc: "Institui o SUSP e a Política Nacional de Segurança Pública e Defesa Social (PNSPDS), integrando as forças policiais. Estabelece princípios comuns: uso moderado da força, respeito aos DH, não discriminação e redução da letalidade policial.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-8", title: "Lei nº 13.869/2019 (Lei do Abuso de Autoridade)", year: "2019", level: "Federal Infralegal", theme: "Abuso de Autoridade / Uso da Força", nature: "Lei Ordinária Federal", desc: "Crimes de abuso de autoridade praticados por agente público no exercício de função pública. Criminaliza o uso excessivo da força. Tipifica violência desnecessária (art. 22), humilhação (art. 28) e submissão a vexame (art. 13). Instrumento central de accountability.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-9", title: "Lei nº 14.751/2023 (Lei Orgânica Nacional das PM e CBM)", year: "2023", level: "Federal Infralegal", theme: "PM e CBM (Lei Orgânica Nacional)", nature: "Lei Ordinária Federal", desc: "Normas gerais de organização das Polícias Militares e Corpos de Bombeiros Militares dos Estados, DF e Territórios. Uniformiza a estrutura, hierarquia, competências e regime disciplinar das PMs, alinhando-as aos princípios constitucionais.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-10", title: "Decreto nº 11.615/2023 (Armas de Fogo – Regulamentação da Lei 10.826/2003)", year: "2023", level: "Federal Infralegal", theme: "Armas de fogo (regulamentação)", nature: "Decreto Federal", desc: "Aquisição, registro, posse, porte, cadastro e comercialização de armas de fogo e itens relacionados. Define termos técnicos (art. 2º); atribui à PF supervisão e normatização do fluxo interno; prevê porte para Auditores-Fiscais. Regula ciclo de armas.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-11", title: "Decreto nº 12.341/2024 (Uso da Força pelos Profissionais de Segurança Pública)", year: "2024", level: "Federal Infralegal", theme: "Uso de força (Segurança Pública)", nature: "Decreto Federal", desc: "Disciplina o uso da força e dos instrumentos de menor potencial ofensivo. Princípios: legalidade, precaução, necessidade, proporcionalidade, razoabilidade, responsabilização e não discriminação (art. 2º). Uso progressivo. Veda uso contra pessoa desarmada em fuga. Cria o CNMUDF.", status: "Vigente", link: "planalto.gov.br" },
  { id: "fi-12", title: "Portaria MJSP nº 855/2025 (Diretrizes sobre Uso da Força – Profissionais de Segurança)", year: "2025", level: "Federal Infralegal", theme: "Uso de força (Segurança Pública)", nature: "Portaria Ministerial Federal", desc: "Estabelece diretrizes operacionais. Uso da força somente para objetivo legal. Prioridade à comunicação e negociação. Veda apontar arma de fogo em abordagens como prática rotineira (art. 10, II). Restringe armas em ambientes prisionais. Alinha padrões ao PBUFAF/ONU.", status: "Vigente (2025)", link: "gov.br/mj" },

  // ==========================================================================
  // EIXO 1 – USO DA FORÇA E SEGURANÇA INTERNACIONAL
  // ==========================================================================
  { id: "in-1", title: "Carta das Nações Unidas (CNU) – art. 2(4), Cap. VI e VII", year: "1945", level: "Internacional", theme: "Uso da Força e Segurança Internacional", nature: "Tratado constitutivo / Hard Law", desc: "Proíbe ameaça ou uso da força contra integridade territorial ou independência política; autoriza força somente por legítima defesa (art. 51) ou mandato do CSNU (Cap. VII). Base do monopólio multilateral da força.", status: "Ratificou 1945", link: "Dec. 19.841/1945" },
  { id: "in-2", title: "Pacto Briand-Kellogg (Tratado de Paris para Renúncia à Guerra)", year: "1928", level: "Internacional", theme: "Uso da Força e Segurança Internacional", nature: "Tratado / Hard Law", desc: "Renúncia à guerra como instrumento de política nacional. Historicamente precursor do art. 2(4) da CNU. Em vigor formal, mas absorvido pela Carta das Nações Unidas.", status: "Ratificou 1934", link: "Dec. 24.557/1934" },
  { id: "in-3", title: "Definição de Agressão – Res. AGNU 3314 (XXIX)", year: "1974", level: "Internacional", theme: "Uso da Força e Segurança Internacional", nature: "Resolução AGNU / Soft Law", desc: "Define agressão armada para fins do art. 39 da CNU. Lista atos qualificados como agressão. Serve de base interpretativa relevante para a jurisdição do TPI (art. 8-bis ER).", status: "Apoiou na AGNU", link: "Sem decreto (res. AGNU)" },
  { id: "in-4", title: "Resolução CSNU 2231 (2015) – Acordo Nuclear Irã (JCPOA)", year: "2015", level: "Internacional", theme: "Uso da Força e Segurança Internacional", nature: "Resolução vinculante / Hard Law", desc: "Endoça e torna obrigatórias restrições nucleares ao Irã; levanta sanções condicionalmente. Exemplo do uso do poder de enforcement do CSNU (Cap. VII) para limitar capacidade militar.", status: "Não é parte do JCPOA", link: "Não aplicável" },
  { id: "in-5", title: "Res. AGNU A/RES/76/17 – Operações de Paz e Uso da Força", year: "2021", level: "Internacional", theme: "Uso da Força e Segurança Internacional", nature: "Resolução AGNU / Soft Law", desc: "Reafirma princípios basilares das operações de manutenção da paz (consentimento, imparcialidade, uso mínimo da força). Regula indiretamente a projeção de força em operações multilaterais.", status: "Apoiou", link: "Sem decreto" },
  { id: "in-6", title: "Convenção sobre a Segurança do Pessoal das Nações Unidas e Associado", year: "1994", level: "Internacional", theme: "Uso da Força e Segurança Internacional", nature: "Tratado / Hard Law", desc: "Criminaliza ataques contra pessoal da ONU em operações de paz; obriga Estados a julgar ou extraditar. Restringe o uso da força contra pessoal humanitário.", status: "Ratificou 2004", link: "Dec. 5.142/2004" },

  // ==========================================================================
  // EIXO 2 – DESARMAMENTO E CONTROLE DE ARMAS
  // ==========================================================================
  { id: "in-7", title: "Tratado sobre a Não Proliferação de Armas Nucleares (TNP)", year: "1968", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe Estados não-nucleares de adquirir armas nucleares; obriga desarmamento progressivo (art. VI); AIEA monitora via salvaguardas. Regime assimétrico que reconhece 5 potências nucleares.", status: "Ratificou 1998", link: "Dec. 2.864/1998" },
  { id: "in-8", title: "Tratado sobre a Proibição de Armas Nucleares (TPAN / TPNW)", year: "2017", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe desenvolvimento, teste, produção, aquisição, posse, armazenamento e uso de armas nucleares. Mais restritivo que o TNP. Potências nucleares não aderiram.", status: "Assinou 2017; não ratificou", link: "Pendente no Congresso" },
  { id: "in-9", title: "Tratado de Proibição Parcial de Testes Nucleares (PTBT)", year: "1963", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe testes nucleares na atmosfera, no espaço exterior e sob a água. Permite testes subterrâneos. Importante precedente histórico de controle de armamentos bilaterais e multilaterais.", status: "Ratificou 1964", link: "Dec. 54.256/1964" },
  { id: "in-10", title: "Tratado de Proibição Completa de Testes Nucleares (CTBT)", year: "1996", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law (Não Vigente)", desc: "Proíbe qualquer explosão nuclear em qualquer ambiente. Monitorado pelo CTBTO. Não entrou em vigor formal por falta de ratificação de 8 Estados específicos do Anexo II.", status: "Ratificou 1998", link: "Dec. 2.864/1998; DL 79/1997" },
  { id: "in-11", title: "Tratado de Tlatelolco (Proscrição de Armas Nucleares na AL e Caribe)", year: "1967", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Cria zona livre de armas nucleares na América Latina e Caribe. Proíbe teste, uso, fabricação, produção ou aquisição de armas nucleares no espaço geográfico delimitado. Mecanismo: OPANAL.", status: "Ratificou 1968", link: "Dec. 63.489/1968" },
  { id: "in-12", title: "New START (Redução e Limitação de Armas Estratégicas Ofensivas)", year: "2010", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado Bilateral / Hard Law", desc: "Limita ogivas nucleares estratégicas e vetores operacionais implantados entre EUA e Rússia. Suspenso pela Rússia em 2023. Exemplo de controle de armas estratégico.", status: "Não é parte", link: "Não aplicável" },
  { id: "in-13", title: "Protocolo de Genebra (Proibição de Gases Asfixiantes e Bacteriológicos)", year: "1925", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe o uso em guerra de gases asfixiantes, venenosos ou similares, e de agentes bacteriológicos. Não proíbe desenvolvimento, produção ou armazenamento.", status: "Ratificou 1970", link: "Dec. 69.586/1972" },
  { id: "in-14", title: "Convenção sobre Armas Químicas (CAQ / CWC)", year: "1993", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe desenvolvimento, produção, aquisição, armazenamento, transferência e uso de armas químicas. Obriga a destruição total de estoques existentes. Verificação conduzida pela OPAQ.", status: "Ratificou 1996", link: "Dec. 2.493/1998" },
  { id: "in-15", title: "Convenção sobre Armas Biológicas e Toxínicas (CABT / BWC)", year: "1972", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe desenvolvimento, produção, armazenamento e uso de armas biológicas e toxínicas. Apresenta como fragilidade estrutural a ausência de um mecanismo formal de verificação.", status: "Ratificou 1973", link: "Dec. 77.374/1976" },
  { id: "in-16", title: "Tratado sobre o Comércio de Armas (TCA / ATT)", year: "2013", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Regula a exportação, importação, trânsito e transbordo de armas convencionais. Obriga a avaliação do risco do uso do armamento em violações de DIH e DIDH.", status: "Ratificou 2018", link: "Dec. 9.368/2018" },
  { id: "in-17", title: "Convenção sobre Certas Armas Convencionais (CCAC / CCW) + 5 Protocolos", year: "1980", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "P-I: fragmentos não detectáveis; P-II (emendado): restringe minas/armadilhas; P-III: restringe armas incendiárias; P-IV: proíbe laser cegante; P-V: regula restos explosivos de guerra.", status: "Ratificou Conv+P-I,II,III (1995); P-IV (1999); P-V (2011)", link: "Dec. 1.570/1995; Dec. 4.100/2002" },
  { id: "in-18", title: "Convenção de Ottawa (Minas Antipessoal / Mine Ban Treaty)", year: "1997", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe completamente o uso, produção, estocagem e transferência de minas antipessoal. Obriga a destruição de estoques em 4 anos e desminagem de territórios em 10 anos.", status: "Ratificou 1999", link: "Dec. 3.229/1999" },
  { id: "in-19", title: "Convenção sobre Munições Cluster (CMC / CCM)", year: "2008", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado / Hard Law", desc: "Proíbe o uso, produção, transferência e armazenamento de munições cluster (submunições que se espalham). Obriga a destruição de estoques e assistência médica e social às vítimas.", status: "Aderiu 2010", link: "Dec. 7.204/2010" },
  { id: "in-20", title: "Tratado sobre Forças Armadas Convencionais na Europa (CFE / FACE)", year: "1990", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado Regional / Hard Law", desc: "Limita carros de combate, veículos blindados, artilharia, aviões e helicópteros na Europa Ocidental e de Leste. Rússia suspendeu participação em 2007 e retirou-se em 2023.", status: "Não é parte", link: "Não aplicável" },
  { id: "in-21", title: "Tratado sobre Mísseis de Alcance Intermediário e Menor (INF)", year: "1987", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado Bilateral / Hard Law", desc: "Eliminava mísseis balísticos e de cruzeiro terrestres com alcances de 500-5.500 km. EUA denunciou em 2019 e Rússia suspendeu participação em 2023, levando à extinção prática.", status: "Não é parte", link: "Não aplicável" },
  { id: "in-22", title: "Tratado Interamericano sobre Transparência nas Aquisições de Armas (TATAAC)", year: "2002", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Tratado Regional / Hard Law", desc: "Obriga os Estados-partes a emitirem relatórios anuais sobre aquisições de armas convencionais para promover a confiança mútua militar na região geográfica das Américas.", status: "Assinou; não ratificou", link: "Pendente" },
  { id: "in-23", title: "Registro de Armas Convencionais da ONU (UNROCA)", year: "1991", level: "Internacional", theme: "Desarmamento e Controle de Armas", nature: "Resolução AGNU / Soft Law", desc: "Convida os Estados a reportarem de forma voluntária as transferências e importações de 7 categorias principais de armas convencionais. Medida de transparência e confiança internacional.", status: "Reporta voluntariamente", link: "Sem decreto (res. AGNU)" },

  // ==========================================================================
  // EIXO 3 – DIREITO INTERNACIONAL HUMANITÁRIO (DIH)
  // ==========================================================================
  { id: "in-24", title: "Convenções de Genebra I, II, III e IV (CG)", year: "1949", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Tratados / Hard Law", desc: "Vértice do Direito de Genebra. CG-I/II: proteção de feridos e doentes; CG-III: prisioneiros de guerra; CG-IV: civis sob autoridade inimiga. Artigo 3 comum estabelece mínimo humanitário aplicável a conflitos internos.", status: "Ratificou 1957", link: "Dec. 42.121/1957" },
  { id: "in-25", title: "Protocolo Adicional I às Convenções de Genebra (PA I) – Conflitos Internacionais", year: "1977", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Protocolo / Hard Law", desc: "Codifica os princípios essenciais de distinção, proporcionalidade e precaução no uso da força armada em hostilidades. Proíbe ataques indiscriminados e protege bens de caráter civil.", status: "Ratificou 1992", link: "Dec. 849/1993" },
  { id: "in-26", title: "Protocolo Adicional II às Convenções de Genebra (PA II) – Conflitos Não Internacionais", year: "1977", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Protocolo / Hard Law", desc: "Amplia as garantias de proteção humana fundamentais aplicáveis a conflitos internos armados (CANI). Proíbe ataques diretos à população civil, fome forçada e deslocamento compulsório.", status: "Ratificou 1992", link: "Dec. 849/1993" },
  { id: "in-27", title: "Protocolo Adicional III às Convenções de Genebra (PA III) – Emblema Adicional", year: "2005", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Protocolo / Hard Law", desc: "Cria o terceiro emblema de proteção internacional regulada (o cristal vermelho), despido de qualquer conotação nacional, política ou religiosa, para salvaguardar pessoal médico e humanitário.", status: "Assinou 2006; não ratificou", link: "Pendente" },
  { id: "in-28", title: "Regulamentos da Haia sobre Leis e Costumes da Guerra Terrestre (Conv. Haia IV)", year: "1907", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Tratado / Hard Law (Costume)", desc: "Pilar do Direito de Haia. Restringe os meios e métodos de combate para evitar sofrimento desnecessário. Contém a Cláusula Martens e proibições ao saque e destruição de propriedade civil.", status: "Ratificou (IV Conv.) 1914", link: "Implícito no Dec. 849/1993" },
  { id: "in-29", title: "Estatuto de Roma do Tribunal Penal Internacional (ER/TPI)", year: "1998", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Tratado / Hard Law", desc: "Cria o TPI com jurisdição sobre crimes de guerra, crimes contra a humanidade, genocídio e crime de agressão. Estabelece a responsabilidade penal individual por violações graves das leis da guerra.", status: "Ratificou 2002", link: "Dec. 4.388/2002" },
  { id: "in-30", title: "Estudo sobre o DIH Consuetudinário (CICV, 2005) – 161 Regras", year: "2005", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Codificação / Soft Law (Interpretativo)", desc: "Trabalho exaustivo de compilação jurídica que identifica 161 regras costumeiras do DIH aplicáveis a conflitos internacionais (CAI) e internos (CANI), servindo de base doutrinária global.", status: "Aplica-se como costume internacional", link: "Sem decreto (costume)" },
  { id: "in-31", title: "Convenção de Haia de 1954 sobre Bens Culturais em Conflito Armado + Protocolos I e II", year: "1954", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Tratado + Protocolos / Hard Law", desc: "Proíbe a utilização de patrimônios ou bens culturais para fins militares e criminaliza ataques contra eles. O Protocolo II (1999) cria a lista de proteção reforçada (nível máximo).", status: "Ratificou Conv. e P-I (1958); P-II: não é parte", link: "Dec. 44.236/1958" },
  { id: "in-32", title: "Declaração de São Petersburgo sobre Projéteis Explosivos", year: "1868", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Declaração / Hard Law (Costume)", desc: "Primeiro acordo oficial moderno que proíbe o uso de armas que causem sofrimento desnecessário (especificamente projéteis explosivos/inflamáveis abaixo de 400 gramas). Incorporada ao costume.", status: "Aplica-se como costume", link: "Sem decreto" },
  { id: "in-33", title: "Manual de Tallinn 2.0 sobre Direito Internacional às Operações Cibernéticas", year: "2017", level: "Internacional", theme: "Direito Internacional Humanitário (DIH)", nature: "Manual Acadêmico / Soft Law", desc: "Análise doutrinária exaustiva que traduz e aplica os limites do DIH e da Carta da ONU para o ambiente virtual das ciberoperações militares estatais. Não possui força vinculante direta.", status: "Não endossou formalmente", link: "Sem decreto" },

  // ==========================================================================
  // EIXO 4 – DIREITOS HUMANOS E MILITARIZAÇÃO
  // ==========================================================================
  { id: "in-34", title: "Pacto Internacional sobre Direitos Civis e Políticos (PIDCP)", year: "1966", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Tratado / Hard Law", desc: "Garante o direito à vida (art. 6), proíbe a tortura (art. 7) e veda prisões arbitrárias (art. 9). Regula limites absolutos a tribunais e detenções militares e lista direitos inderrogáveis em crises (art. 4).", status: "Ratificou 1992", link: "Dec. 592/1992" },
  { id: "in-35", title: "Convenção contra a Tortura (CAT)", year: "1984", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Tratado / Hard Law", desc: "Proíbe de forma absoluta a tortura e tratamentos cruéis por agentes estatais (civis ou militares). Impõe o dever jurídico de investigar, processar criminalmente e punir os transgressores.", status: "Ratificou 1989", link: "Dec. 40/1991" },
  { id: "in-36", title: "Protocolo Facultativo à CAT (OPCAT)", year: "2002", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Protocolo / Hard Law", desc: "Institui um sistema preventivo de visitas e vistorias regulares a locais de privação de liberdade por órgãos internacionais (SPT) e nacionais (MNP). Incidência sobre prisões militares.", status: "Ratificou 2007", link: "Dec. 6.085/2007" },
  { id: "in-37", title: "Código de Conduta para os Funcionários Responsáveis pela Aplicação da Lei (CCFRAL)", year: "1979", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Resolução AGNU / Soft Law", desc: "Consagra o padrão universal de uso mínimo e excepcional da força, proibição absoluta de atos de tortura e a estrita obrigação de proteger a integridade física de indivíduos sob custódia.", status: "Apoiou na AGNU", link: "Sem decreto" },
  { id: "in-38", title: "Princípios Básicos sobre o Uso da Força e Armas de Fogo (PBUFAF)", year: "1990", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Princípios ONU / Soft Law", desc: "Estabelece os pilares da legalidade, necessidade, proporcionalidade e accountability para o emprego coercitivo estatal. Paradigma normativo internacional de controle adotado pelo STF.", status: "Referencia na prática", link: "Sem decreto" },
  { id: "in-39", title: "Declaração Universal dos Direitos Humanos (DUDH)", year: "1948", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Declaração / Soft Law (Costume)", desc: "Texto fundamental estruturante do DIDH moderno. Protege os direitos inalienáveis à vida, liberdade, segurança pessoal (art. 3) e proíbe penas cruéis ou tratamentos degradantes (art. 5).", status: "Votou a favor", link: "Sem decreto" },
  { id: "in-40", title: "Princípios Orientadores sobre Empresas e Direitos Humanos (Princípios Ruggie)", year: "2011", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Princípios ONU / Soft Law", desc: "Determina o dever do Estado de proteger os DH e a responsabilidade das corporações privados de respeitá-los. Aplicável a fornecedores bélicos e empresas de segurança.", status: "Apoiou", link: "Sem decreto" },
  { id: "in-41", title: "Convenção sobre os Direitos das Pessoas com Deficiência (CDPD) + Protocolo Facultativo", year: "2006", level: "Internacional", theme: "Direitos Humanos e Militarização", nature: "Tratado / Hard Law (Valor Const.)", desc: "O artigo 11 impõe a obrigação de adotar medidas de segurança e proteção humanitária específicas para pessoas com deficiência em cenários de conflitos armados e desastres.", status: "Ratificou 2008; Status de Emenda Const.", link: "Dec. 6.949/2009" },

  // ==========================================================================
  // EIXO 5 – MILITARIZAÇÃO DA SEGURANÇA PÚBLICA
  // ==========================================================================
  { id: "in-42", title: "PBUFAF – Incidência Específica Segurança Pública (Eixo 5)", year: "1990", level: "Internacional", theme: "Militarização da Segurança Pública", nature: "Princípios ONU / Soft Law", desc: "Define parâmetros operacionais de prestação de contas, registro e treinamento compulsório para o emprego da força, aplicando-se integralmente a forças militares em missões internas.", status: "Referencia na prática jurídica", link: "Sem decreto" },
  { id: "in-43", title: "Diretrizes da ONU sobre Armas Menos Letais em Aplicação da Lei", year: "2020", level: "Internacional", theme: "Militarização da Segurança Pública", nature: "Diretriz / Soft Law", desc: "Fixa balizamentos técnicos e restrições jurídicas estritas para o uso de armas de menor potencial ofensivo (gás lacrimogênio, balas de borracha, etc.), mitigando abusos de policiamento ostensivo.", status: "Referencia na prática", link: "Sem decreto" },
  { id: "in-44", title: "Convenção Americana sobre Direitos Humanos (Pacto de San José / CADH)", year: "1969", level: "Regional Interamericano", theme: "Militarização da Segurança Pública", nature: "Tratado Regional / Hard Law", desc: "Protege o direito à vida (art. 4), integridade (art. 5) e liberdade (art. 7). Jurisprudência da Corte IDH limita o uso de forças armadas em segurança pública urbana interna (Caso Favela Nova Brasília).", status: "Ratificou 1992; Jurisdição CorIDH (1998)", link: "Dec. 678/1992" },
  { id: "in-45", title: "CCFRAL – Incidência Específica Segurança Pública (Eixo 5)", year: "1979", level: "Internacional", theme: "Militarização da Segurança Pública", nature: "Resolução AGNU / Soft Law", desc: "Estipula deveres funcionais para forças militares quando investidas em atribuições policiais ou de segurança interna: moderação no uso da força e proteção intransigente de detidos.", status: "Apoiou", link: "Sem decreto" },
  { id: "in-46", title: "Conjunto de Princípios para Proteção de Pessoas sob Detenção ou Prisão", year: "1988", level: "Internacional", theme: "Militarização da Segurança Pública", nature: "Resolução AGNU / Soft Law", desc: "Normatiza garantias de tratamento digno a presos e veda incomunicabilidade total. Aplica-se às detenções operadas por forças de segurança civil ou por corporações militares em contexto doméstico.", status: "Referencia na prática", link: "Sem decreto" },

  // ==========================================================================
  // EIXO 6 – CRIANÇAS E CONFLITOS ARMADOS / RECRUTAMENTO MILITAR
  // ==========================================================================
  { id: "in-47", title: "Convenção sobre os Direitos da Criança (CDC)", year: "1989", level: "Internacional", theme: "Crianças e Conflitos Armados", nature: "Tratado / Hard Law", desc: "O artigo 38 impõe o dever de respeitar o DIH e proíbe expressamente o recrutamento militar e a participação direta de menores de 15 anos em hostilidades.", status: "Ratificou 1990", link: "Dec. 99.710/1990" },
  { id: "in-48", title: "Protocolo Facultativo à CDC sobre Crianças em Conflitos Armados (PFCA)", year: "2000", level: "Internacional", theme: "Crianças e Conflitos Armados", nature: "Protocolo / Hard Law", desc: "Eleva o patamar protetivo mínimo para 18 anos contra a participação direta em guerras e proíbe recrutamento obrigatório por grupos irregulares armados. Brasil declarou 17 anos para o voluntário.", status: "Ratificou 2004", link: "Dec. 5.006/2004" },
  { id: "in-49", title: "Convenção 182 da OIT sobre as Piores Formas de Trabalho Infantil", year: "1999", level: "Internacional", theme: "Crianças e Conflitos Armados", nature: "Tratado / Hard Law", desc: "Classifica e tipifica juridicamente o recrutamento forçado e o uso de crianças em conflitos armados como uma das piores formas de trabalho infantil, ordenando sua eliminação penal imediata.", status: "Ratificou 2000", link: "Dec. 3.597/2000" },
  { id: "in-50", title: "Princípios de Paris e Compromissos de Paris (Crianças-Soldados)", year: "2007", level: "Internacional", theme: "Crianças e Conflitos Armados", nature: "Princípios / Soft Law", desc: "Fornece orientações operacionais, psicossociais e técnicas para a desmobilização, liberação segura e reintegração comunitária de crianças ilegalmente associadas a forças ou grupos armados.", status: "Endossou 2007", link: "Sem decreto" },
  { id: "in-51", title: "Resoluções CSNU 1612 (2005) e subsequentes – Mecanismo MRM", year: "2005", level: "Internacional", theme: "Crianças e Conflitos Armados", nature: "Resolução CSNU / Hard e Soft Law", desc: "Cria o Mecanismo de Monitoramento e Relatório (MRM) voltado a registrar e punir seis graves violações institucionais contra crianças em cenários bélicos, listando os entes infratores.", status: "Apoiou no CSNU", link: "Sem decreto" },
  { id: "in-52", title: "Declaração de Genebra sobre Crianças-Soldados (Compromissos de 1999)", year: "1999", level: "Internacional", theme: "Crianças e Conflitos Armados", nature: "Declaração / Soft Law", desc: "Comprometimentos políticos pioneiros de articulação internacional e multilateral voltados a erradicar o uso infantil militarizado, precedendo tecnicamente os Princípios de Paris.", status: "Endossou", link: "Sem decreto" },

  // ==========================================================================
  // EIXO 7 – MERCENÁRIOS E EMPRESAS MILITARES E DE SEGURANÇA PRIVADA (EMSP)
  // ==========================================================================
  { id: "in-53", title: "Convenção Internacional contra Mercenários (ONU Mercenários)", year: "1989", level: "Internacional", theme: "Mercenários e Empresas de Segurança (EMSP)", nature: "Tratado / Hard Law", desc: "Define e criminaliza a atividade mercenária em âmbito internacional; impõe aos Estados-membros o dever de processar ou extraditar o infrator. Apresenta baixa adesão global (37 partes).", status: "Não é parte", link: "Não aplicável" },
  { id: "in-54", title: "Convenção da OUA sobre a Eliminação do Mercenarismo em África", year: "1977", level: "Internacional", theme: "Mercenários e Empresas de Segurança (EMSP)", nature: "Tratado Regional / Hard Law", desc: "Instrumento regional focado no contexto do continente africano. Proíbe os governos de sediarem, financiarem ou facilitarem trânsito a grupos mercenários mercantis armados.", status: "Não é parte (Fora da UA)", link: "Não aplicável" },
  { id: "in-55", title: "Documento de Montreux sobre Obrigações Jurídicas e Boas Práticas (EMSP)", year: "2008", level: "Internacional", theme: "Mercenários e Empresas de Segurança (EMSP)", nature: "Documento Internacional / Soft Law", desc: "Esclarece as obrigações estatais decorrentes do DIH e DIDH aplicáveis à contratação e controle de Empresas Militares e de Segurança Privada (EMSP) em locais de hostilidade.", status: "Não aderiu formalmente", link: "Sem decreto" },
  { id: "in-56", title: "Código Internacional de Conduta para Provedores Privados de Segurança (ICoC)", year: "2010", level: "Internacional", theme: "Mercenários e Empresas de Segurança (EMSP)", nature: "Código de Autorregulação / Soft Law", desc: "Conjunto voluntário de padrões operacionais, auditorias e diretrizes éticas para empresas privadas de segurança, exigindo respeito aos direitos fundamentais e veto a abusos coercitivos.", status: "Não aderiu", link: "Sem decreto" },
  { id: "in-57", title: "Relatório do Grupo de Trabalho da ONU – Proposta de Convenção EMSP", year: "2010", level: "Internacional", theme: "Mercenários e Empresas de Segurança (EMSP)", nature: "Projeto de Tratado / Lex Ferenda", desc: "Proposta jurídica de criação de um tratado internacional vinculante focado na regulação e supervisão estatal de empresas militares de segurança privada. Tramita no Grupo Intergovernamental (OEIGWG).", status: "Participa das negociações", link: "Sem decreto" },
  { id: "in-58", title: "Princípios Ruggie – Incidência Específica EMSP (Eixo 7)", year: "2011", level: "Internacional", theme: "Mercenários e Empresas de Segurança (EMSP)", nature: "Princípios ONU / Soft Law", desc: "Aplica as obrigações de devida diligência empresarial em direitos humanos diretamente sobre as corporações privadas de segurança que operam em contextos de conflito armado.", status: "Apoiou", link: "Sem decreto" },

  // ==========================================================================
  // EIXO 8 – ESPAÇOS INTERNACIONALMENTE REGULADOS
  // ==========================================================================
  { id: "in-59", title: "Tratado Antártico (TA)", year: "1959", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Promove a desmilitarização completa da Antártida. Proíbe o estabelecimento de bases militares, fortificações, testes de armamentos e ensaios nucleares (art. I e V). Autoriza logística militar exclusiva para fins científicos.", status: "Ratificou 1975; Membro Consultivo", link: "Dec. 75.963/1975" },
  { id: "in-60", title: "Tratado sobre Princípios das Atividades no Espaço Exterior (Tratado do Espaço / OST)", year: "1967", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Veda a colocação de armas nucleares ou outras armas de destruição em massa em órbita da Terra, corpos celestes ou espaço sideral (art. IV). Declara corpos celestes zonas inteiramente desmilitarizadas.", status: "Ratificou 1969", link: "Dec. 64.362/1969" },
  { id: "in-61", title: "Tratado de Proibição de Armas Nucleares no Leito do Mar (Seabed Treaty)", year: "1971", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Proíbe expressamente a instalação ou implantação de plataformas e silos de armas nucleares ou outras armas de destruição em massa no fundo do mar e subsolo marinho, além das 12 milhas.", status: "Ratificou 1973", link: "Dec. 72.082/1973" },
  { id: "in-62", title: "Convenção das Nações Unidas sobre o Direito do Mar (CNUDM / UNCLOS)", year: "1982", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Normatiza regimes de trânsito. O regime de passagem inocente (arts. 17-32) veda a ameaça ou uso da força (art. 19.2.a) por belonaves. Delimita fins pacíficos implícitos na Zona/fundos marinhos.", status: "Ratificou 1988", link: "Dec. 99.165/1990" },
  { id: "in-63", title: "Tratado sobre a Lua e outros Corpos Celestes (Tratado da Lua)", year: "1979", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Declara a Lua patrimônio comum da humanidade. Proíbe formalmente bases militares, manobras estratégicas operacionais ou testes bélicos em seu solo. Baixa adesão global (18 partes).", status: "Não é parte", link: "Não aplicável" },
  { id: "in-64", title: "Tratado de Tlatelolco – Incidência Eixo 8 (Espaço Desmilitarizado)", year: "1967", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Consagra pioneiramente a desmilitarização de um espaço geográfico habitado amplo, vedando a proliferação armamentista nuclear estratégica em toda a jurisdição da América Latina.", status: "Ratificou 1968", link: "Dec. 63.489/1968" },
  { id: "in-65", title: "Tratado de Bangkok (Zona Livre de AN no Sudeste Asiático – SEANWFZ)", year: "1995", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado Regional / Hard Law", desc: "Instrumento regional específico firmado pelos países da ASEAN, operando o bloqueio e proscrição de armas atômicas em sua zona territorial e de mar territorial associada.", status: "Não é parte", link: "Não aplicável" },
  { id: "in-66", title: "Convenção sobre a Proibição de Técnicas de Modificação Ambiental para Fins Militares (ENMOD)", year: "1976", level: "Internacional", theme: "Espaços Internacionalmente Regulados", nature: "Tratado / Hard Law", desc: "Proíbe de forma peremptória a utilização militar ou hostil de técnicas que deliberadamente modifiquem o meio ambiente natural (clima, biosfera, litosfera) causando efeitos duradouros.", status: "Ratificou 1984", link: "Dec. 90.158/1984" },

  // ==========================================================================
  // EIXO 9 – PROTEÇÃO DE BENS CIVIS E INFRAESTRUTURAS SENSÍVEIS
  // ==========================================================================
  { id: "in-67", title: "Protocolo Adicional I – Arts. 52-56: Proteção de Bens Civis", year: "1977", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Protocolo / Hard Law (Costume)", desc: "Fixa imunidades: art. 52 proíbe represálias a bens civis; art. 53 veda ataques a monumentos históricos; art. 54 proíbe destruir bens indispensáveis à vida; arts. 55-56 protegem ambiente e usinas.", status: "Ratificou 1992", link: "Dec. 849/1993" },
  { id: "in-68", title: "Resolução CSNU 2286 (2016) – Proteção de Pessoal e Instalações Médicas", year: "2016", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Resolução vinculante / Hard Law", desc: "Condena veementemente ataques contra hospitais, ambulâncias e pessoal médico em guerras. Exige investigações nacionais criminais independentes e proíbe a militarização de clínicas e hospitais.", status: "Apoiou no CSNU", link: "Sem decreto" },
  { id: "in-69", title: "Convenção de Haia de 1954 sobre Bens Culturais – Protocolo I e II", year: "1954", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Tratado + Protocolos / Hard Law", desc: "Incidência material na proteção a acervos. Veda o direcionamento de ataques hostis contra patrimônio histórico-cultural da humanidade, regulando regras de sinalização técnica visual.", status: "Ratificou Conv. e P-I (1958); P-II: não é parte", link: "Dec. 44.236/1958" },
  { id: "in-70", title: "Diretrizes de OCHA / ONU sobre Proteção da Infraestrutura Civil Crítica", year: "2016", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Diretriz / Soft Law", desc: "Recomendações técnicas operacionais para proteção e resguardo de infraestruturas vitais urbanas (redes elétricas, tratamento de água potável, telecomunicações) em cenários de conflitos armados.", status: "Aplica como referência", link: "Sem decreto" },
  { id: "in-71", title: "Diretrizes sobre Proteção de Escolas e Universidades (Safe Schools Declaration)", year: "2015", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Declaração Voluntária / Soft Law", desc: "Compromisso político voluntário que insta os exércitos estatais a não utilizarem instalações escolares ou universitárias para quarteis logísticos operacionais durante operações. 114 signatários.", status: "Não aderiu formalmente", link: "Sem decreto" },
  { id: "in-72", title: "Convenção sobre Armas Químicas (CAQ) – Incidência Eixo 9", year: "1993", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Tratado / Hard Law", desc: "Veda qualquer tipo de emprego tático ou estratégico de agentes químicos contra populações civis e veda impactos colaterais tóxicos deliberados contra infraestruturas agropecuárias ou civis.", status: "Ratificou 1996", link: "Dec. 2.493/1998" },
  { id: "in-73", title: "Princípio da Proporcionalidade e Precaução (Regras CICV 14-24)", year: "2005", level: "Internacional", theme: "Proteção de Bens Civis", nature: "Costume Internacional / Hard Law", desc: "Normas costumeiras universais estruturantes do jus in bello. Proíbem o lançamento de ataques cujos danos colaterais a civis e seus bens ultrapassem a vantagem militar real antecipada.", status: "Aplica-se como costume", link: "Dec. 849/1993 (PA I)" },

  // ==========================================================================
  // EIXO 10 – NORMAS REGIONAIS INTERAMERICANAS
  // ==========================================================================
  { id: "in-74", title: "Carta da Organização dos Estados Americanos (Carta da OEA)", year: "1948", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Tratado constitutivo / Hard Law", desc: "Consagra os princípios fundamentais continentais de não intervenção, solução pacífica de controvérsias regionais e proibição do uso unilateral da força interestatal (arts. 19-22 e 27).", status: "Ratificou 1948", link: "Dec. 30.544/1952" },
  { id: "in-75", title: "Tratado Interamericano de Assistência Recíproca (TIAR)", year: "1947", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Tratado / Hard Law", desc: "Mecanismo jurídico de legítima defesa coletiva hemisférica nas Américas, estipulando que um ataque armado contra um Estado-membro configura agressão contra todos (equivalente art. 51 CNU).", status: "Ratificou 1947", link: "Dec. 26.445/1949" },
  { id: "in-76", title: "Convenção Americana sobre Direitos Humanos (Pacto de São José / CADH)", year: "1969", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Tratado / Hard Law", desc: "Vértice do sistema regional. Garante direitos civis inderrogáveis (vida, integridade). Submete o Brasil à fiscalização contenciosa obrigatória da Comissão Interamericana e da Corte IDH.", status: "Ratificou 1992; Competência CorIDH (1998)", link: "Dec. 678/1992" },
  { id: "in-77", title: "Declaração Americana dos Direitos e Deveres do Homem (DADDH)", year: "1948", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Declaração / Soft Law (Costume)", desc: "Documento precursor histórico do sistema interamericano que lista as prerrogativas fundamentais à segurança pessoal e vida. Aplicada a todos os Estados-membros da OEA pela CIDH.", status: "Adota como Estado-membro", link: "Sem decreto" },
  { id: "in-78", title: "Convenção Interamericana contra o Tráfico Ilícito de Armas (CIFTA)", year: "1997", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Tratado / Hard Law", desc: "Visa combater e penalizar criminalmente a fabricação e o tráfico ilícito de armas de fogo e munições. Determina regras comuns para marcação, rastreamento físico e cooperação policial.", status: "Ratificou 1999", link: "Dec. 3.229/1999 (parcialmente)" },
  { id: "in-79", title: "Declaração sobre Segurança nas Américas (DSA)", year: "2003", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Declaração / Soft Law", desc: "Institui e adota o conceito moderno e multidimensional de segurança hemisférica, aglutinando ameaças tradicionais a novas frentes transnacionais (terrorismo, crime organizado).", status: "Adotou", link: "Sem decreto" },
  { id: "in-80", title: "Convenção sobre Transparência nas Aquisições de Armas Convencionais (TATAAC)", year: "2002", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Tratado Regional / Hard Law", desc: "Prevê o intercâmbio de dados e notificações prévias recíprocas sobre compras e importações de equipamentos de combate pesado entre as nações, visando reduzir desconfianças táticas.", status: "Assinou; não ratificou", link: "Pendente no Senado Federal" },
  { id: "in-81", title: "Res. AGNU A/RES/73/27 – Informação e Telecomunicações na Segurança", year: "2018", level: "Internacional", theme: "Normas Regionais Interamericanas", nature: "Resolução AGNU / Soft Law", desc: "Reflete o consenso emergente global de que os regramentos fundamentais do direito internacional clássico, incluindo a Carta da ONU e o DIH, incidem plenamente no ciberespaço.", status: "Copatrocinou", link: "Sem decreto" },
  { id: "in-82", title: "Tratado de Tlatelolco – Incidência Regional (Eixo 10)", year: "1967", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Tratado / Hard Law", desc: "Exemplo histórico regional de articulação diplomática bem-sucedida para banimento de capacidades estratégicas ofensivas de destruição em massa na vizinhança geopolítica.", status: "Ratificou 1968", link: "Dec. 63.489/1968" },
  { id: "in-83", title: "Resolução 1/2020 da CIDH – Pandemia e Direitos Humanos nas Américas", year: "2020", level: "Regional Interamericano", theme: "Normas Regionais Interamericanas", nature: "Resolução CIDH / Soft Law", desc: "Fixa diretrizes estritas para a atuação excepcional das forças armadas e de polícia em estados de emergência sanitária, proibindo expressamente o uso excessivo ou discriminatório da força.", status: "Aplica-se", link: "Sem decreto" }
];